#!/bin/sh

# Always use neovim
alias vim="nvim" vimdiff="nvim -d"

# Dotfiles repo control
alias dotfiles="git --git-dir=$HOME/.config/dotfiles-srv.git/ --work-tree=$HOME"

# Verbosity and interactivity settings
alias                \
  cp="cp -iv"        \
  mv="mv -iv"        \
  rm="rm -vI"        \
  ln="ln -v"         \
  mkd="mkdir -pv"    \
  rsync="rsync -hP"  \

# Colorize commands when possible
alias                                                   \
  ls="ls -hN --color=auto --group-directories-first"    \
  ll="ls -lAhN --color=auto --group-directories-first"  \
  grep="grep --color=auto"                              \
  diff="diff --color=auto"                              \
  ccat="highlight --out-format=ansi"                    \

# Common commands abbreviation
alias                               \
  e="$EDITOR"                       \
  E="sudo $EDITOR"                  \
  s="sudo su -l"                    \
  q="exit"                          \
  ka="killall"                      \
  p="ping"                          \
  S="systemctl"                     \
  sS="sudo systemctl"               \
  J="journalctl"                    \
  sJ="sudo journalctl"              \
  h="history -i -100000 | less +G"  \
  hs="history -i -100000 | grep"    \
